### PR TITLE
Update and Clean up smi2sdf, min_oe_openMM, and examples

### PR DESCRIPTION
**Pull request by bannanc**
I am trying to clean up the long for loop that is used for all the different minimizations. I mostly changed the prepGAFF and prepSMIRFF to actually do the minimizations. I removed all of the continues so in theory you could do all of the force fields, except that GAFF and GAFF2 would need separate directories, currently only one GAFF directory is passed. 

I have some ideas about input, but I'll list the idea here and then we can talk about what makes the most sense.

### CODE REVIEW

**Comment by bannanc** [comment]
I have some ideas about how to call the script from the command line that would let you run all force fields without the `FFTYPE` input. 

Here's what I propose:
```
python ffcompare.py --inmols [mol2s] --ffxml [optional] --gaffdir [directory] --gaff2dir [directory] --doMMFF [True or False] 
```

--inmols would be the only required. 

Then if you have ffxml you would do smirff, gaffdir run gaff, gaff2dir run gaff2, doMMFF True run that section. 

I also think the intro line on `load_and_minimize` could be this instead:
```
def load_and_minimize(infiles, dommff = False, ffxml = None, gaffdir = None, gaff2dir = None
```
Then instead of checking for "do..." you would check for `if not [thing] is None` except for the dommff option. 

@vtlim I'm happy to code this up, but I want feedback first since it would change actual use cases. 
I'd like your feedback @dkyu

**Comment by vtlim** [comment]
I'm also on board with your suggested changes to the command line arguments and the `load_and_minimize` function.

**Comment by bannanc** [comment]
@vtlim and @dkyu 

I had forgot about this, I have a lot of work I'm hoping to get done today and tomorrow before David's ACS talk. I'll try to get the new version on this working later this week so Daisy could use it for eMolecule soon.

**Comment by bannanc** [comment]
@vtlim I think this is ready when ever you have time to look it over.

I smi2sdf, genMOL2.py, and min_oe_openMM.py on the example set of molecules in examples and everything worked smoothly.

**Comment by vtlim** [comment]
@bannanc Could we do the renaming section later? It's not showing differences in ffcompare.py and min_oe_openMM.py since it's treating them as separate files, one deleted and one added.

**Comment by vtlim** [comment]
Also regarding examples, it seems repetitive/unwieldy to add almost 100 files when they just do the same thing to a set of molecules. I'm thinking we could trim the initial SMILES file to 3-5 molecules, and run through the workflow with that, which should be plenty indicative.

**Comment by bannanc** [comment]
@vtlim I shrunk the example to two molecules. I moved the name back to ffcompare for now, you can see the differences in the file again. 

I also updated smi2sdf to make it runable from the command line.

**Pull request merged**
